// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lxuvtfxcigwxxekmsjqo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imx4dXZ0ZnhjaWd3eHhla21zanFvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjA2NTQyNzUsImV4cCI6MjA3NjIzMDI3NX0.VKV4JltjqnO9F6ZSfo7t5o5EP6T8W7u4JIO8yD3iZ7g";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});